name = "Gruppe Adler Anti-personnel obstacle breaching system";
author = "";
logo = "logo_ca.paa";
logoOver = "logo_active_ca.paa";
tooltip = "Gruppe Adler Anti-personnel obstacle breaching system";
tooltipOwned = "Gruppe Adler Anti-personnel obstacle breaching system";
picture = "overview_co.paa";
actionName = "GitHub";
action = "https://github.com/gruppe-adler/grad_apobs";
overview = "<br/><t align='center' size='0.75'>Visit Gruppe Adler on <t href='https://gruppe-adler.de/'>our Website</t> | <t href='http://discord.gruppe-adler.de'>Discord</t> | <t href='https://www.youtube.com/user/gruppeadler'>YouTube</t> | <t href='https://twitter.com/Gruppe_Adler'>Twitter</t></t><br/><br/>";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.8196, 0.5529, 0.1216, 1};
logoSmall = "logo_small_ca.paa";